
  The maximum ratio of deformation speed to wave speed is 0.33283 in element
  385 of instance PART-1-1 at increment 612.


  The maximum ratio of deformation speed to wave speed is 0.39349 in element
  385 of instance PART-1-1 at increment 613.


  The maximum ratio of deformation speed to wave speed is 0.46969 in element
  385 of instance PART-1-1 at increment 614.


  The maximum ratio of deformation speed to wave speed is 0.55120 in element
  385 of instance PART-1-1 at increment 615.


  The maximum ratio of deformation speed to wave speed is 0.58177 in element
  385 of instance PART-1-1 at increment 616.


  The maximum ratio of deformation speed to wave speed is 0.57224 in element
  396 of instance PART-1-1 at increment 617.


  The maximum ratio of deformation speed to wave speed is 0.50830 in element
  396 of instance PART-1-1 at increment 618.


  The maximum ratio of deformation speed to wave speed is 0.42503 in element
  396 of instance PART-1-1 at increment 619.


  The maximum ratio of deformation speed to wave speed is 0.38255 in element
  385 of instance PART-1-1 at increment 620.


  The maximum ratio of deformation speed to wave speed is 0.39609 in element
  385 of instance PART-1-1 at increment 621.


  The maximum ratio of deformation speed to wave speed is 0.44968 in element
  50 of instance PART-1-1 at increment 622.


  The maximum ratio of deformation speed to wave speed is 0.45192 in element
  50 of instance PART-1-1 at increment 623.


  The maximum ratio of deformation speed to wave speed is 0.41155 in element
  47 of instance PART-1-1 at increment 624.


  The maximum ratio of deformation speed to wave speed is 0.50533 in element
  47 of instance PART-1-1 at increment 625.


  The maximum ratio of deformation speed to wave speed is 0.57274 in element
  347 of instance PART-1-1 at increment 626.


  The maximum ratio of deformation speed to wave speed is 0.48908 in element
  347 of instance PART-1-1 at increment 627.


  The maximum ratio of deformation speed to wave speed is 0.52190 in element
  82 of instance PART-1-1 at increment 628.


  The maximum ratio of deformation speed to wave speed is 0.63288 in element
  49 of instance PART-1-1 at increment 629.


  The maximum ratio of deformation speed to wave speed is 0.49881 in element
  99 of instance PART-1-1 at increment 630.


  The maximum ratio of deformation speed to wave speed is 0.69754 in element
  102 of instance PART-1-1 at increment 631.


  The maximum ratio of deformation speed to wave speed is 0.75532 in element
  82 of instance PART-1-1 at increment 632.


  The maximum ratio of deformation speed to wave speed is 1.7083 in element 82
  of instance PART-1-1 at increment 633.

